resolver: lts-17.11
compiler: ghc-9.0.1
allow-newer: true
system-ghc: true

packages:
- '.'

extra-deps:
- doctest-0.18.1

nix:
  enable: true
  shell-file: shell-stack.nix
  path: ["nixpkgs=./nixpkgs.nix"]
