# See https://hub.docker.com/r/tweag/linear-types/
resolver: lts-14.6
compiler: ghc-8.9
allow-newer: true
system-ghc: true

packages:
- '.'

# We must use a more recent version of primitive due to MonadFail
# Hedgehog requires a newer version of constraints
extra-deps:
  - primitive-0.7.0.0
  - constraints-0.11
  - hedgehog-1.0.2
  - tasty-hedgehog-1.0.0.2
  - optparse-applicative-0.15.1.0


nix:
  shell-file: shell-stack.nix
  path: ["nixpkgs=./nixpkgs.nix"]
