steps:
  - label: "Install linear-types enabled GHC"
    command: |
      nix-shell --command ''
    timeout: 120
    key: "install-linear-ghc"
  - label: "Run tests (cabal-install)"
    command: |
      nix-shell --pure --run 'cabal update; cabal test'
    timeout: 30
    depends_on: "install-linear-ghc"
